name: Daily Twisted

on:
  repository_dispatch:
   
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Luvit (official installer)
        run: |
          curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh
          ./lit make luvit

      - name: Decrypt bot code
        run: |
          openssl aes-256-cbc -d -pbkdf2 -in TwistedBot.lua.enc -out TwistedBot.lua -pass pass:"${{ secrets.BOT_KEY }}"

      - name: Run Daily Twisted bot
        run: |
          ./luvit TwistedBot.lua send
